language: node_js
node_js:
- lts/*
git:
  depth: 3
addons:
  apt:
    packages:
    - expect-dev
cache:
- pip
- npm
install:
- npm ci
before_install:
- |
  if [ $TRAVIS_BRANCH == "future" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then
    openssl aes-256-cbc -K $encrypted_d4a09416a845_key -iv $encrypted_d4a09416a845_iv -in .staging.key.json.enc -out .staging.key.json -d
    gcloud auth activate-service-account --key-file=.staging.key.json
  fi
stages:
- preparation
- name: build
  if: branch = future AND type != pull_request
- name: deploy
  if: branch = future AND type != pull_request
jobs:
  include:
  - stage: preparation
    env: APP_ENV=staging
    name: Check code, import documents, build samples, playground & boilerplate
    before_script:
    - scripts/unbuffer.sh gulp buildSamples
    - scripts/unbuffer.sh gulp buildComponentVersions
    - scripts/unbuffer.sh npm test
    script:
    - if [ $TRAVIS_BRANCH == "future" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then scripts/unbuffer.sh gulp buildPrepare; fi
  - stage: build
    env: APP_ENV=staging
    install: &1
    - npm ci
    - pip install grow==0.7.4 --user
    name: Build Pages (EN)
    script: scripts/unbuffer.sh gulp buildPages --locales en
  - stage: build
    env: APP_ENV=staging
    install: *1
    name: Build Pages (FR)
    script: scripts/unbuffer.sh gulp buildPages --locales fr
  - stage: build
    env: APP_ENV=staging
    install: *1
    name: Build Pages (AR)
    script: scripts/unbuffer.sh gulp buildPages --locales ar
  - stage: build
    env: APP_ENV=staging
    install: *1
    name: Build Pages (ES)
    script: scripts/unbuffer.sh gulp buildPages --locales es
  - stage: build
    env: APP_ENV=staging
    install: *1
    name: Build Pages (IT)
    script: scripts/unbuffer.sh gulp buildPages --locales it
  - stage: build
    env: APP_ENV=staging
    install: *1
    name: Build Pages (ID)
    script: scripts/unbuffer.sh gulp buildPages --locales id
  - stage: build
    env: APP_ENV=staging
    install: *1
    name: Build Pages (JA)
    script: scripts/unbuffer.sh gulp buildPages --locales ja
  - stage: build
    env: APP_ENV=staging
    install: *1
    name: Build Pages (KO)
    script: scripts/unbuffer.sh gulp buildPages --locales ko
  - stage: build
    env: APP_ENV=staging
    install: *1
    name: Build Pages (BR)
    script: scripts/unbuffer.sh gulp buildPages --locales pt_BR
  - stage: build
    env: APP_ENV=staging
    install: *1
    name: Build Pages (RU)
    script: scripts/unbuffer.sh gulp buildPages --locales ru
  - stage: build
    env: APP_ENV=staging
    install: *1
    name: Build Pages (TR)
    script: scripts/unbuffer.sh gulp buildPages --locales tr
  - stage: build
    env: APP_ENV=staging
    install: *1
    name: Build Pages (CN)
    script: scripts/unbuffer.sh gulp buildPages --locales zh_CN
  - stage: deploy
    env: APP_ENV=staging
    before_script:
    - scripts/unbuffer.sh gulp buildFinalize
    - scripts/unbuffer.sh npm run smoke-test
    script:
    - gcloud app deploy --project=amp-dev-staging --quiet --version=1
