runtime: custom
env: flex
env_variables:
  APP_PORT: '8080'
  APP_ENV: 'staging'
manual_scaling:
  instances: 1
readiness_check:
  app_start_timeout_sec: 500
resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 20
