# Redirects for amp.dev
# External targets are possible
# The paths specified as source will work with all configured locales.
# Request query parameters of the original request are appended to the redirect
#
# The first section contains basic shortcuts
# (For shortened deep links please use go.amp.dev/shortcut and the file 'go-links.yaml')
#
# The second part contains other redirects (e.g. moved pages)

### Shortcuts
# These shortcuts are intended for basic pages (not deeplinks)
# Ensure you do not use shortcuts that would shadow real contents
# Add new entries in alphabetical order in the format /path/to/old/url: /path/to/new/url

/ads: /about/ads/
/docs: /documentation/guides-and-tutorials/
/email: /about/email/
/learn: /documentation/courses/
/samples: /documentation/examples/
/stories: /about/stories/
/websites: /about/websites/

### Other redirects
# Put here redirects for pages that have been moved, etc
# Add new entries in alphabetical order in the format /path/to/old/url: /path/to/new/url

/documentation/examples/interactivity-dynamic-content/autosuggest_form/: /documentation/examples/components/amp-autocomplete/
/documentation/examples/interactivity-dynamic-content/simple_autosuggest/: /documentation/examples/components/amp-autocomplete/
/documentation/guides-and-tutorials/learn/amp-email-format: /documentation/guides-and-tutorials/learn/email-spec/amp-email-format/
/documentation/guides-and-tutorials/contribute/ad-integration-guide/: /documentation/guides-and-tutorials/contribute/vendor-contributions/ad-integration-guide/
/documentation/guides-and-tutorials/contribute/integrate-your-tech/: /documentation/guides-and-tutorials/contribute/vendor-contributions/
/documentation/guides-and-tutorials/develop/amp_story_best_practices/: /documentation/guides-and-tutorials/start/create_successful_stories/
/documentation/guides-and-tutorials/optimize-measure/configure-analytics/: /documentation/guides-and-tutorials/optimize-and-measure/configure-analytics/
/documentation/guides-and-tutorials/optimize-measure/configure-analytics/analytics-vendors: /documentation/guides-and-tutorials/optimize-and-measure/configure-analytics/analytics-vendors/
/documentation/guides-and-tutorials/optimize-measure/configure-analytics/analytics_basics: /documentation/guides-and-tutorials/optimize-and-measure/configure-analytics/analytics_basics/
/documentation/guides-and-tutorials/optimize-measure/configure-analytics/deep_dive_analytics: /documentation/guides-and-tutorials/optimize-and-measure/configure-analytics/deep_dive_analytics/
/documentation/guides-and-tutorials/optimize-measure/configure-analytics/use_cases: /documentation/guides-and-tutorials/optimize-and-measure/configure-analytics/use_cases/
/community/platform-and-vendor-partners: /support/faq/platform-and-vendor-partners/
/examples/source/user-consent/basic_user_consent_flow: /examples/source/user-consent/client_side_user_consent_flow/
