# Use via: go.amp.dev/ads
# Add new entries in alphabetical order
/ads: /about/ads/
/amp-pwa-amp: https://blog.amp.dev/2018/06/19/the-shadow-reader-improved/
/ampcs: /events/amp-cs-2019/#Schedule
/auto-sw: https://github.com/ampproject/amp-sw/
/camp-code: https://github.com/ampproject/samples/tree/master/amp-camp
/cherry-picks: https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks
/contribute/code: https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md
/contribute/code-samples: /documentation/guides-and-tutorials/contribute/contribute-documentation/formatting/?format=websites#preview-code-samples
/contribute/docs: /documentation/guides-and-tutorials/contribute/contribute-documentation/
/contribute/samples: /documentation/examples/
/contribute/translations: /documentation/guides-and-tutorials/contribute/translations/
/cors: /documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cors-requests/
/design-reviews: https://github.com/ampproject/amphtml/issues?q=is%3Aissue+is%3Aopen+design+review+utc+in%3Atitle
/devx-survey: https://google.qualtrics.com/jfe/form/SV_2f10wnLh8qJclRb
/docs: /documentation/guides-and-tutorials/
/docsgfi: https://github.com/ampproject/amp.dev/issues?q=is:open+is:issue+label:%22good+first+issue%22
/email: /about/email/
/email-support: /support/faq/email-support/
/email-tools: /documentation/tools/?format=email
/email-viewer: https://github.com/ampproject/amp-email-viewer
/governance: /community/governance/
/i2i: https://github.com/ampproject/amphtml/issues/new?assignees=&labels=INTENT+TO+IMPLEMENT&template=intent-to-implement--i2i-.md&title=I2I:%20%3Cyour%20change/update%3E
/io-email: /documentation/examples/interactivity-dynamic-content/conference_survey_email/
/learn: /documentation/courses/
/learn-first: /documentation/guides-and-tutorials/start/create/
/learn-advanced: /documentation/guides-and-tutorials/start/add_advanced/
/learn-email: /documentation/guides-and-tutorials/learn/email_fundamentals/?format=email
/learn-interact: /documentation/guides-and-tutorials/develop/interactivity/
/learn-story: /documentation/guides-and-tutorials/start/visual_story/?format=stories
/learn-pwa: https://codelabs.developers.google.com/codelabs/amp-pwa-workbox/
/learn-script: /documentation/guides-and-tutorials/develop/custom-javascript-tutorial/
/optimize-amp: https://blog.amp.dev/2018/10/08/how-to-make-amp-even-faster/
/owners: https://ampproject-owners-bot.appspot.com/tree
/publishing-checklist: /documentation/guides-and-tutorials/optimize-and-measure/publishing_checklist/
/reftemplate: https://docs.google.com/document/d/1lRFcErFBnqsuv6W9mZsfYk2qnXO9nPzMkeog4Xtunl8/edit?usp=sharing
/shopify-apps: https://blog.amp.dev/2019/04/15/shopify-apps-make-amp-easy-and-effective-for-ecommerce
/stories-best-practices: /documentation/guides-and-tutorials/develop/amp_story_best_practices/
/stories: /about/stories/
/sxg: /documentation/guides-and-tutorials/optimize-and-measure/signed-exchange/
/templates: /documentation/templates/
/test-email: /documentation/guides-and-tutorials/develop/testing_amp_emails/?format=email
/tools: /documentation/tools/
/vision-mission: /about/mission-and-vision/
/websites: /about/websites/
/wg: https://github.com/ampproject/meta/tree/master/working-groups
/wg-updates: https://github.com/search?o=desc&q=org%3Aampproject+label%3A%22Type%3A+Status+Update%22&s=created&

# Regex-based entries
^/c/amp-([a-z-]+)$:
  url: /documentation/components/amp-$1
  useRegex: true
^/e/amp-([a-z-]+)$:
  url: /documentation/examples/components/amp-$1/
  useRegex: true
^/pr/([0-9]+)$:
  url: https://github.com/ampproject/amphtml/pull/$1
  useRegex: true
^/issue/([0-9]+)$:
  url: https://github.com/ampproject/amphtml/issues/$1
  useRegex: true
